// Date: 5/26/2013 9:03:22 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ccm.harvestry.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelJuicer extends ModelBase
{

    // fields
    ModelRenderer Base;

    ModelRenderer TopA;

    ModelRenderer TopB;

    ModelRenderer Center;

    ModelRenderer Blade;

    public ModelJuicer()
    {
        textureWidth = 64;
        textureHeight = 64;

        this.Base = new ModelRenderer(this, 0, 0);
        this.Base.addBox(0F, 0F, 0F, 12, 4, 12);
        this.Base.setRotationPoint(-6F, 20F, -6F);
        this.Base.setTextureSize(64, 64);
        this.Base.mirror = true;
        this.setRotation(this.Base, 0F, 0F, 0F);
        this.TopA = new ModelRenderer(this, 0, 16);
        this.TopA.addBox(0F, 0F, 0F, 10, 9, 10);
        this.TopA.setRotationPoint(-5F, 11F, -5F);
        this.TopA.setTextureSize(64, 64);
        this.TopA.mirror = true;
        this.setRotation(this.TopA, 0F, 0F, 0F);
        this.TopB = new ModelRenderer(this, 50, 9);
        this.TopB.addBox(0F, 0F, 0F, 3, 3, 3);
        this.TopB.setRotationPoint(-4F, 8F, 1F);
        this.TopB.setTextureSize(64, 64);
        this.TopB.mirror = true;
        this.setRotation(this.TopB, 0F, 0F, 0F);
        this.Center = new ModelRenderer(this, 0, 0);
        this.Center.addBox(0F, 0F, 0F, 2, 7, 2);
        this.Center.setRotationPoint(-1F, 13F, -1F);
        this.Center.setTextureSize(64, 64);
        this.Center.mirror = true;
        this.setRotation(this.Center, 0F, 0F, 0F);
        this.Blade = new ModelRenderer(this, 32, 0);
        this.Blade.addBox(0F, 0F, 0F, 8, 0, 8);
        this.Blade.setRotationPoint(-4F, 19F, -4F);
        this.Blade.setTextureSize(64, 64);
        this.Blade.mirror = true;
        this.setRotation(this.Blade, 0F, 0F, 0F);
    }

    public void render(final Entity entity, final float f, final float f1, final float f2, final float f3, final float f4, final float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.Base.render(f5);
        this.TopA.render(f5);
        this.TopB.render(f5);
        this.Center.render(f5);
        this.Blade.render(f5);
    }

    private void setRotation(final ModelRenderer model, final float x, final float y, final float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(final float f, final float f1, final float f2, final float f3, final float f4, final float f5, final Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
